### ISSUE TITLE
Updated Assets

### ISSUE THREAD

**Issue by NewsGuyTor** [tverona1/QuestAppLauncher_Assets#1]
The assets are becoming seriously outdated now, they haven't been updated since August.

I've added some (most?) of the new Quest games since the last update, it's in the attached files.

[iconpack.zip](https://github.com/tverona1/QuestAppLauncher_Assets/files/3908883/iconpack.zip)
[appnames.json.zip](https://github.com/tverona1/QuestAppLauncher_Assets/files/3908885/appnames.json.zip)

**Comment by tverona1** [comment]
Thanks - I just updated with latest Quest releases
